pipeline {
    agent any
    tools {
       maven 'LocalMaven'
       jdk   'LocalJDK' 
    }
    stages {
        stage('build_CaseStudy') {
          steps {
              echo "Building for Case Study.....!!"
              sh 'mvn compile'
           }
    }
    stage('test') {
          steps {
              echo "Tesing.....!!"
              sh 'mvn test'
           }
    }
  }
}
